### ISSUE TITLE
Latest Update changed behavior of color overrides

### ISSUE THREAD

**Issue by apolzon** [sheerun/sublime-wombat-theme#1]
Not sure when this update got pushed out, but I noticed it when I restarted sublime this morning.

Previously (and still according to the README, near as I can tell), if you wanted to use, say, the red wombat colors, you would do:

`wombat_color_red: true`

Now, however, setting red to true does not override the enabling of the blue color, so you have to add:
`wombat_color_blue: false`
to properly disable the default and allow your override to take effect.

**Comment by sheerun** [comment]
Thank you for reporting this issue.

Since 1.3.0 wombat is gray by default, and color overrides work as expected. Sorry for delay.
