### ISSUE TITLE
Folder Tree Structure is not showing properly

### ISSUE THREAD

**Issue by pankajpatel** [sheerun/sublime-wombat-theme#10]
The folder tree structure is not showing properly,
seems like built for mac only. Is there any work arround? Black icons and text???
![1](https://cloud.githubusercontent.com/assets/251937/3705126/7b4c864c-141b-11e4-8d24-1c43dce199fc.jpg)
![2](https://cloud.githubusercontent.com/assets/251937/3705125/7b473ae8-141b-11e4-9d65-1c0fe8be29e9.jpg)

**Comment by sheerun** [comment]
Did you restart sublime?

**Comment by pankajpatel** [comment]
My Bad...!! 
Restarted and its fine now!!!
