### ISSUE TITLE
Doubled folder icons

### ISSUE THREAD

**Issue by sirpeas** [sheerun/sublime-wombat-theme#11]
Hi,
you have to add these lines to Wombat's settings to avoid double folder icons (Default and yours)

```
{
    "class": "icon_file_type",
    "content_margin": [0,0]
},
{
    "class": "icon_folder",
    "content_margin": [0,0]
},
{
    "class": "icon_folder_loading",
    "content_margin": [0,0]
}
```

![screen shot 2014-09-01 at 13 31 57](https://cloud.githubusercontent.com/assets/4818642/4107724/a7a649d0-31cb-11e4-92dd-62fd8d25f0dc.png)

**Comment by sheerun** [comment]
Is it configuratoin for ST2 or ST3?

**Comment by sirpeas** [comment]
ST3, I mean that I tested it only on ST3, because I only use ST3.

**Comment by sheerun** [comment]
It was little more than this: https://github.com/sheerun/sublime-wombat-theme/commit/fcc2fb84d617911843c2f6c2e454f94fa0bf23d0

New theme should be available to update in few hours I think.
