### ISSUE TITLE
ST3 - Sidebar alignment

### ISSUE THREAD

**Issue by rbraaf** [sheerun/sublime-wombat-theme#14]
I've tested this theme on two new installs of sublime text 3 and found that the 'x' icons in the sidebar are being cut off. I've also tested with using the default settings in ST. Please see the attached screenshot.

![screen shot 2015-03-10 at 8 06 18 am](https://cloud.githubusercontent.com/assets/9223060/6574543/9aad4dac-c6fc-11e4-919f-391aab51cf09.png)

**Comment by sheerun** [comment]
Mind creating a PR with fix? :)
