### ISSUE TITLE
Getting wired theme. Pls help

### ISSUE THREAD

**Issue by Himanshu-Mishr** [sheerun/sublime-wombat-theme#3]
Hi , I have been using your theme for long time. Its my favorite. But from 2 days when package control updated itself to 2.0 , and when I restarted editor I got something like this ... see the screen-shot. So to see where problem was , I freshly installed ST2 and installed package control. Till that time everything was OK , but when I installed wombat-them through package control, I am getting something like in screen shot. Sorry for my bad English . Please help me how to correct this.
I am using Ubuntu 13.04 and have installed ST 2.0.2 .

![screenshot from 2013-08-11 19 53 57](https://f.cloud.github.com/assets/1938285/947429/04b6a938-0353-11e3-87f4-696de82876ec.png)
![screenshot from 2013-08-11 19 56 01](https://f.cloud.github.com/assets/1938285/947438/301b8fa8-0353-11e3-8733-82a1d2e2e9e0.png)

**Comment by sheerun** [comment]
Could you paste all output somewhere online? That would help me.

**Comment by sheerun** [comment]
The upgrade of all of ST3 packages literally destroyed my editor :) I'll try to install it from scratch.

@edit
In case of any problems during upgrade, remove Wombat Theme and install it again. It helped in my case.

**Comment by sheerun** [comment]
Abut you problem, works for me on ST2.0.2 + package control 2.0.0 on OSX 10.9. I'll install Ubuntu VM.

**Comment by Himanshu-Mishr** [comment]
This is Ctrl + ` output.   http://pastebin.com/xv2Ar8H5 . And thank you for your quick response.

**Comment by sheerun** [comment]
Well, according to that output Wombat is probably not installed. Could you try to remove any Wombat-related settings form your User configuration, remove Wombat, install Wombat, and add that configuration again?

**Comment by Himanshu-Mishr** [comment]
Got it, did what you said. Thanks for your support. :)  I love this theme.

**Comment by sheerun** [comment]
Just to be sure. It worked for you?

**Comment by Himanshu-Mishr** [comment]
Yes. :+1: 
![screenshot from 2013-08-12 22 13 39](https://f.cloud.github.com/assets/1938285/948733/865cb57a-036e-11e3-84c0-84294054499d.png)

**Comment by sheerun** [comment]
OK :)  I managed to install sublime in the same environment. I guess it is upgrade issue. I'm closing until someone re-creates this issue again. Please paste here full output though.
