### ISSUE TITLE
Removes the fullscreen button on OSX

### ISSUE THREAD

**Issue by davoclavo** [sheerun/sublime-wombat-theme#4]
Installing Wombat through the package manager removes the fullscreen button on OSX.

The bug affects both, sublimetext v2 and v3

**Comment by davoclavo** [comment]
I just realized this can be toggled by setting:

`"use_simple_full_screen": false`

Am I missing something or why is this simple full screen mode useful?

**Comment by sheerun** [comment]
It's faster to switch to fullscreen (no animation), and it plays nicer with
multiple monitors (Mavericks solves this problem, but it's not released
yet).

If you give me some reason to keep the default one I'm more than eager to
roll it back :) Unfortunately I don't think that lack of full screen button
is a good one (you can use shortcut).

**Comment by davoclavo** [comment]
I rarely switch between fullscreen to windowed, so animation time is not really important for me, but I do get your point.

About multiple monitors, I totally agree with you. Usually I develop on one monitor, so I don't realize how bad it is.

More than the button per se, it jumped me because it changed the behavior of fullscreen apps. I thought Sublime had an update that removed fullscreen native behavior.

I would recommend to change the default to `false`. It is a nice feature that I think I will start to use, but it was weird as a newcomer. I thought my sublime was broken, not that was a feature of a package.

:+1:

**Comment by sheerun** [comment]
I still think use_simple_full_screen is better default, but I updated installation message to make it clear.
