### ISSUE TITLE
Build output 

### ISSUE THREAD

**Issue by yichuan1118** [sheerun/sublime-wombat-theme#6]
After installed Wombat plugin, the texts in build output panel are pushed to the left, half of the first column is blocked by the window boarder.

Sublime text 3 
Linux Mint 16

![screenshot from 2013-11-25 14 41 15](https://f.cloud.github.com/assets/957901/1611022/ca57760e-559c-11e3-99c3-107ec7dcbd32.png)

**Comment by sheerun** [comment]
Hey. Did you restart sublime after installation?

**Comment by yichuan1118** [comment]
Yes, I did. I also tried disabling all options changed by the plugin, didn't work :/

**Comment by sheerun** [comment]
Does the https://github.com/buymeasoda/soda-theme or https://github.com/netatoo/phoenix-theme work for you?

**Comment by yichuan1118** [comment]
Yes, I have tried both. At least the build output window look fine.

**Comment by yichuan1118** [comment]
BTW, I can confirm that the same problem exists on Windows 8 64bit (sublime3) as well

**Comment by sheerun** [comment]
@yichuan1118 I removed offending setting (negative margin), this should work now. Please remove & install wombat again if you still use it.
