### ISSUE TITLE
How to manually install?

### ISSUE THREAD

**Issue by mkaizumi** [sheerun/sublime-wombat-theme#9]
this is what I do, I download it, I extract it and put on browse package folder via sublime

follow the intruction given, edit a line in User for theme
and this happen

![2014-04-02_9-44-03](https://cloud.githubusercontent.com/assets/7073051/2586709/77a94704-ba08-11e3-9c8a-2d2cdffec518.png)

**Comment by sheerun** [comment]
Please use package manager, put following in user config:

```
{
  "theme": "Wombat.sublime-theme",
  "wombat_color_blue": true,
  "wombat_dirty_bottom_bar_blue": true,
  "color_scheme": "Packages/Wombat Theme/Wombat.tmTheme",
}
```

And restart sublime.

**Comment by sheerun** [comment]
If you install manually you need to make sure the folder you extracted to is `Wombat Theme`

**Comment by mkaizumi** [comment]
Tq for helping me, now its work when I change the folder name, I guess you might miss to explain to change the folder name to Wombat Theme :)
